
console.log("||------------------------------------------------------------------------||")
console.log("||------------------------------------------------------------------------||")
console.log("||                       SANJAY MEMORIAL ITNER COLLEGE                    ||")
console.log("||                              Year(2021-2022)                           ||")
console.log("||------------------------------------------------------------------------||")
console.log("||------------------------------------------------------------------------||")
console.log("||                                                                        ||")
console.log("||    Name     | Class  | Roll No  | Section  | Subject | Marks  |  Grade ||")
console.log("||             |        |          |          |         |        |        ||")
console.log("||  Suhel Khan |   X    |    21    |    A     |  Math   |  85%   |   A2   ||")
console.log("||             |        |          |          |         |        |        ||")
console.log("||  Mohd Hamza |   X    |    47    |    A     |  Math   |  71%   |   B1   ||")
console.log("||             |        |          |          |         |        |        ||")
console.log("||  Amir ali   |   X    |    48    |    A     |  Math   |  90%   |   A1   ||")
console.log("||             |        |          |          |         |        |        ||")
console.log("||                                                                        ||")
console.log("||                                                                        ||")
console.log("||                                                                        ||")
console.log("||                                                                        ||")
console.log("||                                                                        ||")
console.log("||                                                                        ||")
console.log("||                                                                        ||")
console.log("||                                                                        ||")
console.log("||                                                                        ||")
console.log("||                                                                        ||")
console.log("||                                                                        ||")
console.log("||                                                                        ||")
console.log("||------------------------------------------------------------------------||")
console.log("||------------------------------------------------------------------------||")
